spring:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshoppingdb?createDatabaseIfNotExist=true
    username: root
    password: password
